NYUROOT=~/data/nyudepth_trainval/

mogrify -format jpg $NYUROOT/train/basement/*.ppm
mogrify -format jpg $NYUROOT/train/bathroom/r-129*.ppm
mogrify -format jpg $NYUROOT/train/bathroom/r-130*.ppm
mogrify -format jpg $NYUROOT/train/bathroom/r-131*.ppm
mogrify -format jpg $NYUROOT/train/bedroom/r-129*.ppm
mogrify -format jpg $NYUROOT/train/bedroom/r-130*.ppm
mogrify -format jpg $NYUROOT/train/bedroom/r-131*.ppm
mogrify -format jpg $NYUROOT/train/bookstore/r-1295525*.ppm
mogrify -format jpg $NYUROOT/train/bookstore/r-1295526*.ppm
mogrify -format jpg $NYUROOT/train/cafe/*.ppm
mogrify -format jpg $NYUROOT/train/computer_lab/*.ppm
mogrify -format jpg $NYUROOT/train/conference_room/*.ppm
mogrify -format jpg $NYUROOT/train/dentist_office/*.ppm
mogrify -format jpg $NYUROOT/train/dinette/*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13151*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13152*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13153*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13154*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13155*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13156*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13157*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13158*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13159*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13160*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13161*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13162*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13163*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13164*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13165*.ppm
mogrify -format jpg $NYUROOT/train/dining_room/r-13166*.ppm
mogrify -format jpg $NYUROOT/train/excercise_room/*.ppm
mogrify -format jpg $NYUROOT/train/foyer/*.ppm
mogrify -format jpg $NYUROOT/train/furniture_store/*.ppm
mogrify -format jpg $NYUROOT/train/home_office/*.ppm
mogrify -format jpg $NYUROOT/train/home_storage/*.ppm
mogrify -format jpg $NYUROOT/train/indoor_balcony/*.ppm
mogrify -format jpg $NYUROOT/train/kitchen/r-129*.ppm
mogrify -format jpg $NYUROOT/train/kitchen/r-130*.ppm
mogrify -format jpg $NYUROOT/train/kitchen/r-131*.ppm
mogrify -format jpg $NYUROOT/train/laundry_room/*.ppm
mogrify -format jpg $NYUROOT/train/library/*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-129*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-130*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13151*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13152*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13153*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13154*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13155*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13156*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13157*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13158*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-13159*.ppm
mogrify -format jpg $NYUROOT/train/living_room/r-1316*.ppm
mogrify -format jpg $NYUROOT/train/nyu_office/*.ppm
mogrify -format jpg $NYUROOT/train/office/*.ppm
mogrify -format jpg $NYUROOT/train/office_kitchen/*.ppm
mogrify -format jpg $NYUROOT/train/patio/*.ppm
mogrify -format jpg $NYUROOT/train/playroom/*.ppm
mogrify -format jpg $NYUROOT/train/printer_room/*.ppm
mogrify -format jpg $NYUROOT/train/reception_room/*.ppm
mogrify -format jpg $NYUROOT/train/student_lounge/*.ppm
mogrify -format jpg $NYUROOT/train/study/*.ppm
mogrify -format jpg $NYUROOT/train/study_room/*.ppm


mogrify -format jpg $NYUROOT/val/basement/*.ppm
mogrify -format jpg $NYUROOT/val/bathroom/r-129*.ppm
mogrify -format jpg $NYUROOT/val/bathroom/r-130*.ppm
mogrify -format jpg $NYUROOT/val/bathroom/r-131*.ppm
mogrify -format jpg $NYUROOT/val/bedroom/r-129*.ppm
mogrify -format jpg $NYUROOT/val/bedroom/r-130*.ppm
mogrify -format jpg $NYUROOT/val/bedroom/r-131*.ppm
mogrify -format jpg $NYUROOT/val/bookstore/r-1295525*.ppm
mogrify -format jpg $NYUROOT/val/bookstore/r-1295526*.ppm
mogrify -format jpg $NYUROOT/val/cafe/*.ppm
mogrify -format jpg $NYUROOT/val/computer_lab/*.ppm
mogrify -format jpg $NYUROOT/val/conference_room/*.ppm
mogrify -format jpg $NYUROOT/val/dentist_office/*.ppm
mogrify -format jpg $NYUROOT/val/dinette/*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13154*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13155*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13156*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13157*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13158*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13159*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13160*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13161*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13162*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13163*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13164*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13165*.ppm
mogrify -format jpg $NYUROOT/val/dining_room/r-13166*.ppm
mogrify -format jpg $NYUROOT/val/excercise_room/*.ppm
mogrify -format jpg $NYUROOT/val/foyer/*.ppm
mogrify -format jpg $NYUROOT/val/furniture_store/*.ppm
mogrify -format jpg $NYUROOT/val/home_office/*.ppm
mogrify -format jpg $NYUROOT/val/home_storage/*.ppm
mogrify -format jpg $NYUROOT/val/indoor_balcony/*.ppm
mogrify -format jpg $NYUROOT/val/kitchen/r-129*.ppm
mogrify -format jpg $NYUROOT/val/kitchen/r-130*.ppm
mogrify -format jpg $NYUROOT/val/kitchen/r-131*.ppm
mogrify -format jpg $NYUROOT/val/laundry_room/*.ppm
mogrify -format jpg $NYUROOT/val/library/*.ppm
mogrify -format jpg $NYUROOT/val/living_room/r-129*.ppm
mogrify -format jpg $NYUROOT/val/living_room/r-130.ppm
mogrify -format jpg $NYUROOT/val/living_room/r-131*.ppm
mogrify -format jpg $NYUROOT/val/nyu_office/*.ppm
mogrify -format jpg $NYUROOT/val/office/*.ppm
mogrify -format jpg $NYUROOT/val/office_kitchen/*.ppm
mogrify -format jpg $NYUROOT/val/patio/*.ppm
mogrify -format jpg $NYUROOT/val/playroom/*.ppm
mogrify -format jpg $NYUROOT/val/printer_room/*.ppm
mogrify -format jpg $NYUROOT/val/reception_room/*.ppm
mogrify -format jpg $NYUROOT/val/student_lounge/*.ppm
mogrify -format jpg $NYUROOT/val/study/*.ppm
mogrify -format jpg $NYUROOT/val/study_room/*.ppm



